### PR TITLE
integrating eslint in the pipeline

### PR DESCRIPTION
**Pull request by tylp**

### CODE REVIEW

**Comment by tylp** [comment]
Added the eslint check in our actions.
Note that the warnings won't fail the pipeline.

Should close #87 if accepted.

**Comment by adrien-nf** [comment]
@tylp Is there a way to make it so that the warning fails the pipelines ?

**Comment by tylp** [comment]
> 
> 
> @tylp Is there a way to make it so that the warning fails the pipelines ?

Added eslint command argument. It now fails the pipeline in case of a warning.

**Comment by adrien-nf** [comment]
Perfect! I'm currently fixing the eslint compilation errors, and will merge on top of this branch, so we can merge this branch in main. Thanks a lot!

**Review by adrien-nf — APPROVED** [review]

**Pull request merged**
