### PR TITLE
Rename "I Packed my Suitcase" to "I Packed my Bag"

### PR DESCRIPTION
**Pull request by adrien-nf**
This is the actual name of the game.

### CODE REVIEW

**Comment by adrien-nf** [comment]
@tylp @vbouillennec @cyrilgourgouillon @nathangobinet Any update on this?

**Comment by vbouillennec** [comment]
@adrien-nf  https://www.youtube.com/watch?v=eFUc7ln2PKI

**Review by cyrilgourgouillon — APPROVED** [review]
LGTM !

**Review by tylp — APPROVED** [review]
This should probably be "I packed my bag, forever"

**Pull request merged**
